/**
 * Thai translations for interface text. The key is the English text exactly as
 * it is written in the page; English mode simply shows the key, so a missing
 * entry falls back to English instead of showing nothing.
 */
export const TH_UI: Record<string, string> = {
  "Financial Reputation Intelligence": "ข้อมูลเชิงลึกด้านชื่อเสียงทางการเงิน",
  "Understand a business": "เข้าใจธุรกิจ",
  "before you trust it.": "ก่อนที่คุณจะไว้ใจ",
  "FRL turns scattered financial records into a structured reputation signal — one you can inspect, question, and trace back to its source. Where evidence is missing, FRL says so rather than guessing.": "FRL เปลี่ยนบันทึกทางการเงินที่กระจัดกระจายให้เป็นสัญญาณชื่อเสียงที่เป็นระบบ ซึ่งคุณตรวจสอบ ตั้งคำถาม และสืบย้อนไปถึงแหล่งที่มาได้ หากไม่มีหลักฐาน FRL จะบอกตรงๆ ไม่เดา",
  "Search a company": "ค้นหาบริษัท",
  "How FRL works": "FRL ทำงานอย่างไร",
  "Signal composition": "องค์ประกอบของสัญญาณ",
  "Evidence to reputation": "จากหลักฐานสู่ชื่อเสียง",
  "Conceptual": "เชิงแนวคิด",
  "Structure illustration. FRL reports": "ภาพประกอบโครงสร้าง หากไม่มีหลักฐานรองรับ FRL จะรายงานว่า",
  "rather than a score when no supporting evidence exists.": "แทนการให้คะแนน",
  "Search company by name or registration ID": "ค้นหาบริษัทด้วยชื่อหรือเลขทะเบียน",
  "company": "บริษัท",
  "Popular:": "ยอดนิยม:",
  "Product preview": "ตัวอย่างผลิตภัณฑ์",
  "One company, fully accounted for.": "หนึ่งบริษัท ข้อมูลครบทุกด้าน",
  "A FRL profile separates what a company looks like from what can actually be demonstrated about it. Identity, source, verification state and reputation dimensions sit side by side — including the dimensions that have nothing behind them yet.": "โปรไฟล์ FRL แยกภาพลักษณ์ของบริษัทออกจากสิ่งที่พิสูจน์ได้จริง ตัวตน แหล่งที่มา สถานะการยืนยัน และมิติชื่อเสียงวางเคียงกัน รวมถึงมิติที่ยังไม่มีข้อมูลรองรับ",
  "Reg:": "ทะเบียน:",
  "Demo record": "ข้อมูลตัวอย่าง",
  "Business reputation": "ชื่อเสียงทางธุรกิจ",
  "Demo score — not real": "คะแนนตัวอย่าง — ไม่ใช่ของจริง",
  "Illustrative preview of a development demo record.": "ตัวอย่างประกอบจากข้อมูลทดลองสำหรับการพัฒนา",
  "Capabilities": "ความสามารถ",
  "Built for reading a business carefully.": "สร้างมาเพื่ออ่านธุรกิจอย่างรอบคอบ",
  "Four capabilities, each answering a different question about a counterparty — and each declining to answer when the record is not there.": "สี่ความสามารถ แต่ละอย่างตอบคำถามต่างกันเกี่ยวกับคู่ค้า และจะไม่ตอบเมื่อไม่มีบันทึกรองรับ",
  "Method": "วิธีการ",
  "Evidence, in the order it is used.": "หลักฐาน ตามลำดับที่ใช้งานจริง",
  "A reputation signal is never the first step. It is the last — and it can only be reached if every step before it actually had something to work with.": "สัญญาณชื่อเสียงไม่ใช่ขั้นแรก แต่เป็นขั้นสุดท้าย และจะไปถึงได้ก็ต่อเมื่อทุกขั้นก่อนหน้ามีข้อมูลให้ทำงานจริง",
  "If step one returns nothing, FRL stops there and reports Insufficient Data. It does not estimate a score to fill the gap.": "หากขั้นแรกไม่ได้ข้อมูล FRL จะหยุดแล้วรายงานว่าข้อมูลไม่พอ ไม่ประมาณคะแนนมาอุดช่องว่าง",
  "Start with a company.": "เริ่มจากบริษัทหนึ่งแห่ง",
  "Look up a business by name or registration number and see exactly what FRL holds — and exactly what it does not.": "ค้นหาธุรกิจด้วยชื่อหรือเลขทะเบียน แล้วดูว่า FRL มีข้อมูลอะไร และไม่มีอะไร",
  "Search companies": "ค้นหาบริษัท",
  "Read the principles": "อ่านหลักการ",
  "FRL": "FRL",
  "Financial Reputation Layer. A registry record is not an FRL verification, and an absence of evidence is reported as such.": "Financial Reputation Layer ข้อมูลจากทะเบียนไม่ใช่การยืนยันโดย FRL และการไม่มีหลักฐานจะถูกรายงานตามจริง",
  "Product": "ผลิตภัณฑ์",
  "My company profile": "โปรไฟล์บริษัทของฉัน",
  "Principles": "หลักการ",
  "Demo records shown in this preview are development sample data and are never presented as verified companies.": "ข้อมูลตัวอย่างในหน้านี้ใช้เพื่อการพัฒนาเท่านั้น และจะไม่ถูกแสดงเป็นบริษัทที่ยืนยันแล้ว",
  "Scroll to travel": "เลื่อนเพื่อเดินทาง",
  "Evidence before opinion": "หลักฐานมาก่อนความเห็น",
  "Provenance on every record": "ทุกบันทึกมีที่มา",
  "Source and retrieval state always shown.": "แสดงแหล่งที่มาและสถานะการดึงข้อมูลเสมอ",
  "Honest absence": "บอกตรงๆ เมื่อไม่มี",
  "Missing evidence reported, never imputed.": "รายงานหลักฐานที่ขาด ไม่เดาเติม",
  "Explainable signals": "สัญญาณที่อธิบายได้",
  "Each dimension describes what it measured.": "แต่ละมิติอธิบายว่าวัดอะไร",
  "Identity resolved from a public registry record": "ระบุตัวตนจากบันทึกทะเบียนสาธารณะ",
  "Source and retrieval status shown per record": "แสดงแหล่งที่มาและสถานะการดึงข้อมูลของทุกบันทึก",
  "Dimensions that lack evidence read Insufficient Data": "มิติที่ไม่มีหลักฐานจะแสดงว่าข้อมูลไม่พอ",
  "Reputation Intelligence": "ข้อมูลเชิงลึกด้านชื่อเสียง",
  "A structured read of how a business has behaved financially, expressed as named dimensions rather than an opaque number.": "การอ่านพฤติกรรมทางการเงินของธุรกิจอย่างเป็นระบบ แสดงเป็นมิติที่มีชื่อ ไม่ใช่ตัวเลขที่ไม่รู้ที่มา",
  "Evidence-Based Signals": "สัญญาณจากหลักฐาน",
  "Every signal traces back to the record it came from. Where evidence is absent, FRL reports Insufficient Data instead of estimating.": "ทุกสัญญาณสืบย้อนไปถึงบันทึกต้นทางได้ หากไม่มีหลักฐาน FRL จะรายงานว่าข้อมูลไม่พอแทนการประมาณ",
  "Company Intelligence": "ข้อมูลเชิงลึกของบริษัท",
  "Corporate identity resolved from public registry records, so a profile is anchored to a real entity before anything else is said.": "ระบุตัวตนบริษัทจากทะเบียนสาธารณะ โปรไฟล์จึงยึดกับนิติบุคคลจริงก่อนจะพูดเรื่องอื่น",
  "Transparent Analysis": "การวิเคราะห์ที่โปร่งใส",
  "Explanations travel with the result. You can see the source, the retrieval status, and what remains unknown.": "คำอธิบายมาพร้อมผลลัพธ์ คุณเห็นแหล่งที่มา สถานะการดึงข้อมูล และสิ่งที่ยังไม่รู้",
  "Evidence": "หลักฐาน",
  "Records actually held": "บันทึกที่มีอยู่จริง",
  "Signals": "สัญญาณ",
  "Derived from that evidence": "สรุปจากหลักฐานนั้น",
  "Analysis": "การวิเคราะห์",
  "Interpreted, not assumed": "ตีความ ไม่ใช่สันนิษฐาน",
  "Reputation": "ชื่อเสียง",
  "Reported with provenance": "รายงานพร้อมที่มา",
  "Unclaimed": "ยังไม่มีเจ้าของรับรอง",
  "Type": "ประเภท",
  "Verification": "การยืนยัน",
  "Retrieved": "ดึงข้อมูลเมื่อ",
  "Demo data — not a real score": "ข้อมูลตัวอย่าง — ไม่ใช่คะแนนจริง",
  "Insufficient data": "ข้อมูลไม่พอ",
  "View profile": "ดูโปรไฟล์",
  "FIND": "FIND",
  "Business intelligence": "ข้อมูลเชิงลึกธุรกิจ",
  "Find a business": "ค้นหาธุรกิจ",
  "Search business records and inspect the evidence available to FRL. A registry record identifies a company; it is not itself a verification, and not every record carries financial evidence.": "ค้นหาบันทึกธุรกิจและตรวจหลักฐานที่ FRL มี บันทึกทะเบียนระบุตัวบริษัท แต่ไม่ใช่การยืนยัน และไม่ใช่ทุกบันทึกจะมีหลักฐานทางการเงิน",
  "Search company by name or registration number": "ค้นหาบริษัทด้วยชื่อหรือเลขทะเบียน",
  "Enter": "Enter",
  "Two characters or more. FRL queries the public corporate registry.": "อย่างน้อยสองตัวอักษร FRL ค้นจากทะเบียนบริษัทสาธารณะ",
  "Registry provider not configured": "ยังไม่ได้ตั้งค่าผู้ให้บริการทะเบียน",
  "Search results": "ผลการค้นหา",
  "Results for": "ผลการค้นหาสำหรับ",
  "Unable to complete the search": "ค้นหาไม่สำเร็จ",
  "Reference:": "รหัสอ้างอิง:",
  "Try again": "ลองอีกครั้ง",
  "Registry results": "ผลจากทะเบียน",
  "Development demo records": "ข้อมูลตัวอย่างสำหรับพัฒนา",
  "Sample data for local development. These are NOT real registry records and are never presented as verified companies.": "ข้อมูลตัวอย่างสำหรับการพัฒนา ไม่ใช่บันทึกทะเบียนจริง และจะไม่ถูกแสดงเป็นบริษัทที่ยืนยันแล้ว",
  "No matching businesses": "ไม่พบธุรกิจที่ตรงกัน",
  "Try another business name or identifier.": "ลองใช้ชื่อหรือเลขอ้างอิงธุรกิจอื่น",
  "Registry retrieval is not FRL verification. Records listed as demo data are development samples and are never presented as verified companies.": "การดึงข้อมูลจากทะเบียนไม่ใช่การยืนยันโดย FRL ข้อมูลที่ระบุว่าเป็นตัวอย่างใช้เพื่อการพัฒนาเท่านั้น และจะไม่ถูกแสดงเป็นบริษัทที่ยืนยันแล้ว",
  "Loading search directory…": "กำลังโหลดไดเรกทอรีค้นหา…",
  "Enter a company name or registration identifier to search the registry.": "ใส่ชื่อบริษัทหรือเลขทะเบียนเพื่อค้นหาในทะเบียน",
  "5 System Principles (P1–P5)": "5 หลักการของระบบ (P1–P5)",
  "STRICT SPECIFICATION": "ข้อกำหนดที่เข้มงวด",
  "EVIDENCE HIERARCHY": "ลำดับชั้นหลักฐาน",
  "Official Documents": "เอกสารทางการ",
  "Self-declared documents. FRL records the tier and does not verify the document against an authority.": "เอกสารที่เจ้าของแจ้งเอง FRL บันทึกระดับหลักฐาน แต่ไม่ได้ตรวจกับหน่วยงานที่เกี่ยวข้อง",
  "Counterparty Attestation": "การรับรองโดยคู่ค้า",
  "Dual digital sign-off / Direct counterparty verification link": "ลงนามดิจิทัลสองฝ่าย / ลิงก์ยืนยันโดยตรงจากคู่ค้า",
  "Public Review": "รีวิวสาธารณะ",
  "Qualitative feedback only; strictly isolated from reputation axes": "เป็นความเห็นเชิงคุณภาพเท่านั้น แยกจากแกนชื่อเสียงโดยเด็ดขาด",
  "No Single Score": "ไม่มีคะแนนรวม",
  "Selective Disclosure": "เลือกเปิดเผย",
  "Insufficient Data ≠ Bad": "ข้อมูลไม่พอ ≠ แย่",
  "System as Evidence-Provider": "ระบบเป็นผู้ให้หลักฐาน",
  "Decay & Right to Restart": "ข้อมูลเสื่อมอายุ และสิทธิ์เริ่มใหม่",
  "Financial Reputation Layer": "Financial Reputation Layer",
  "Evidence before opinion.": "หลักฐานมาก่อนความเห็น",
  "No conclusion without a record behind it.": "ไม่มีข้อสรุปใดที่ไม่มีบันทึกรองรับ",
  "Email": "อีเมล",
  "Password": "รหัสผ่าน",
  "← Back to FRL": "← กลับไป FRL",
  "Welcome back": "ยินดีต้อนรับกลับ",
  "Create your account": "สร้างบัญชีของคุณ",
  "Log in to manage your claims.": "เข้าสู่ระบบเพื่อจัดการ claim ของคุณ",
  "Create an account to manage your claims.": "สร้างบัญชีเพื่อจัดการ claim ของคุณ",
  "Log in": "เข้าสู่ระบบ",
  "Create account": "สร้างบัญชี",
  "Please wait…": "กรุณารอสักครู่…",
  "Do not have an account? Create one": "ยังไม่มีบัญชี? สร้างบัญชี",
  "Already have an account? Log in": "มีบัญชีแล้ว? เข้าสู่ระบบ",
  "FRL Owner Portal": "พอร์ทัลเจ้าของ FRL",
  "Logged in as": "เข้าสู่ระบบในนาม",
  "Create Verification Link": "สร้างลิงก์ยืนยัน",
  "Select the claims you want to disclose to your counterparty. They will only see the true/false status and evidence tier, not your raw data.": "เลือก claim ที่ต้องการเปิดเผยให้คู่ค้า เขาจะเห็นเพียงสถานะจริง/เท็จและระดับหลักฐาน ไม่เห็นข้อมูลดิบของคุณ",
  "Expires:": "หมดอายุ:",
  "Generate Unique Link": "สร้างลิงก์เฉพาะ",
  "Link Generated Successfully": "สร้างลิงก์สำเร็จ",
  "Share this link securely. Every access is logged and you can revoke it at any time.": "แชร์ลิงก์นี้อย่างปลอดภัย ทุกการเข้าถึงถูกบันทึกไว้ และคุณเพิกถอนได้ทุกเมื่อ",
  "Back to Profile": "กลับไปโปรไฟล์",
  "Request Counterparty Attestation": "ขอให้คู่ค้ารับรอง",
  "Turn your track record into verified reputation. Ask a trusted counterparty to attest to a specific business interaction. Once verified, this becomes a claim backed by the \"Counterparty Attested\" evidence tier.": "เปลี่ยนประวัติการทำงานให้เป็นชื่อเสียงที่ยืนยันแล้ว ขอให้คู่ค้าที่ไว้ใจรับรองธุรกรรมใดธุรกรรมหนึ่ง เมื่อยืนยันแล้วจะกลายเป็น claim ระดับหลักฐาน \"รับรองโดยคู่ค้า\"",
  "Counterparty Name or Email": "ชื่อหรืออีเมลคู่ค้า",
  "Reputation Axis": "แกนชื่อเสียง",
  "Reliability (e.g. Paid on time)": "ความน่าเชื่อถือ (เช่น จ่ายตรงเวลา)",
  "Resilience (e.g. Handled supply chain shock)": "ความยืดหยุ่น (เช่น รับมือปัญหาห่วงโซ่อุปทาน)",
  "Leverage (e.g. Maintained healthy debt ratio)": "สัดส่วนหนี้ (เช่น รักษาอัตราหนี้ให้เหมาะสม)",
  "Statement to Attest": "ข้อความที่ขอให้รับรอง",
  "Send Attestation Request": "ส่งคำขอรับรอง",
  "Request Sent Successfully": "ส่งคำขอสำเร็จ",
  "Your counterparty has received a secure link to review and sign your attestation statement.": "คู่ค้าของคุณได้รับลิงก์ปลอดภัยสำหรับตรวจและลงนามในข้อความรับรองแล้ว",
  "Return to Profile": "กลับไปโปรไฟล์",
  "Active": "ใช้งานอยู่",
  "Expired": "หมดอายุ",
  "Revoked": "ถูกเพิกถอน",
  "Create New Link": "สร้างลิงก์ใหม่",
  "Manage Claims": "จัดการ claim",
  "View and revoke active claims. Revoked claims immediately stop resolving via verification links.": "ดูและเพิกถอน claim ที่ใช้งานอยู่ claim ที่ถูกเพิกถอนจะหยุดแสดงผ่านลิงก์ยืนยันทันที",
  "Created:": "สร้างเมื่อ:",
  "Revoked on:": "เพิกถอนเมื่อ:",
  "Revoke Access": "เพิกถอนการเข้าถึง",
  "Audit Log": "บันทึกการตรวจสอบ",
  "The owner of this reputation revoked the link. It is no longer a valid disclosure, so FRL shows no reputation data for it.": "เจ้าของชื่อเสียงนี้เพิกถอนลิงก์แล้ว จึงไม่ใช่การเปิดเผยที่ใช้ได้ FRL จึงไม่แสดงข้อมูลชื่อเสียงของลิงก์นี้",
  "This disclosure link has passed its expiry date. It is no longer valid, so FRL shows no reputation data for it.": "ลิงก์เปิดเผยนี้เลยวันหมดอายุแล้ว จึงใช้ไม่ได้ FRL จึงไม่แสดงข้อมูลชื่อเสียงของลิงก์นี้",
  "The reputation owner chose what to disclose from this link. FRL displays only what the link is configured to release.": "เจ้าของชื่อเสียงเลือกสิ่งที่จะเปิดเผยผ่านลิงก์นี้ FRL แสดงเฉพาะสิ่งที่ลิงก์ตั้งค่าให้เปิดเผย",
  "The proof behind this link is not active. FRL shows no reputation data for it.": "หลักฐานเบื้องหลังลิงก์นี้ไม่อยู่ในสถานะใช้งาน FRL จึงไม่แสดงข้อมูลชื่อเสียง",
  "Company": "บริษัท",
  "Disclosure level": "ระดับการเปิดเผย",
  "Disclosed reputation score": "คะแนนชื่อเสียงที่เปิดเผย",
  "Disclosed reputation factors": "ปัจจัยชื่อเสียงที่เปิดเผย",
  "No reputation score, level or factor result is shown for this link.": "ลิงก์นี้ไม่แสดงคะแนน ระดับ หรือผลปัจจัยชื่อเสียง",
  "Verified": "ยืนยันแล้ว",
  "Link expires": "ลิงก์หมดอายุ",
  "Evidence policy": "นโยบายหลักฐาน",
  "This information was selectively shared by the reputation owner. No raw financial information is exposed through this link.": "ข้อมูลนี้เจ้าของชื่อเสียงเลือกแชร์ ลิงก์นี้ไม่เปิดเผยข้อมูลการเงินดิบ",
  "FRL only displays a score, a level and factor results for a proof that is active and was produced under the current reputation evidence policy.": "FRL แสดงคะแนน ระดับ และผลปัจจัย เฉพาะหลักฐานที่ยังใช้งานอยู่และออกภายใต้นโยบายหลักฐานชื่อเสียงปัจจุบัน",
  "Back to company search": "กลับไปค้นหาบริษัท",
  "This proof is active. FRL displays the reputation it recorded at the verification date below, and nothing else.": "หลักฐานนี้ยังใช้งานอยู่ FRL แสดงชื่อเสียงที่บันทึกไว้ ณ วันยืนยันด้านล่างเท่านั้น ไม่มีอย่างอื่น",
  "Proof reference": "รหัสอ้างอิงหลักฐาน",
  "Reputation factors": "ปัจจัยชื่อเสียง",
  "Expires": "หมดอายุ",
  "Scan to open this verification": "สแกนเพื่อเปิดการยืนยันนี้",
  "Reputation is a snapshot taken on": "ชื่อเสียงนี้เป็นภาพ ณ วันที่",
  "and may change afterwards. No raw financial information is exposed through this verification.": "และอาจเปลี่ยนแปลงภายหลัง การยืนยันนี้ไม่เปิดเผยข้อมูลการเงินดิบ",
  "No FRL record matches this reference. FRL displays no reputation, score or claim for a reference it cannot resolve.": "ไม่มีบันทึก FRL ที่ตรงกับรหัสอ้างอิงนี้ FRL ไม่แสดงชื่อเสียง คะแนน หรือ claim ของรหัสที่หาไม่พบ",
  "The following statements were submitted to FRL and authorised by": "ข้อความต่อไปนี้ถูกส่งให้ FRL และได้รับอนุมัติโดย",
  "for your review.": "เพื่อให้คุณตรวจสอบ",
  "This is a restricted disclosure and the access has been recorded in the FRL audit trail. Raw financial data is never exposed. Each statement below carries the evidence tier it was submitted with, so you can judge how it was established.": "นี่คือการเปิดเผยแบบจำกัด และการเข้าถึงถูกบันทึกในบันทึกตรวจสอบของ FRL ข้อมูลการเงินดิบจะไม่ถูกเปิดเผย ทุกข้อความด้านล่างระบุระดับหลักฐานที่ส่งมา เพื่อให้คุณประเมินได้ว่าได้มาอย่างไร",
  "This claim is no longer active and cannot be relied upon.": "claim นี้ไม่ได้ใช้งานแล้ว และไม่ควรใช้อ้างอิง",
  "Active claim": "claim ที่ใช้งานอยู่",
  "Evidence tier": "ระดับหลักฐาน",
  "Valid until": "ใช้ได้ถึง",
  "FRL records what a party submits and the tier it was submitted at. It does not audit the underlying evidence and does not guarantee the outcome described in a claim.": "FRL บันทึกสิ่งที่ฝ่ายหนึ่งส่งมาและระดับที่ส่ง ไม่ได้ตรวจสอบหลักฐานเบื้องหลัง และไม่รับประกันผลลัพธ์ที่ claim ระบุ",
  "Lowest Weight Tier": "ระดับน้ำหนักต่ำสุด",
  "Loading reviews...": "กำลังโหลดรีวิว...",
  "EXCELLENT": "ยอดเยี่ยม",
  "GOOD": "ดี",
  "FAIR": "พอใช้",
  "LOW": "ต่ำ",
  "INSUFFICIENT DATA": "ข้อมูลไม่พอ",
  "Only you see this page. FRL gives you a score once your records are complete, and shows nothing it has not calculated.": "มีแต่คุณที่เห็นหน้านี้ FRL จะให้คะแนนเมื่อบันทึกของคุณครบ และไม่แสดงสิ่งที่ยังไม่ได้คำนวณ",
  "See public profile": "ดูโปรไฟล์สาธารณะ",
  "Real Data": "ข้อมูลจริง",
  "Demo Mode": "โหมดตัวอย่าง",
  "Profile": "โปรไฟล์",
  "Demo Mode.": "โหมดตัวอย่าง",
  "Showing the built-in sample profile": "กำลังแสดงโปรไฟล์ตัวอย่างในระบบ",
  ". Nothing here is real evidence, and no score on this screen is a real reputation.": ". ไม่มีสิ่งใดในนี้เป็นหลักฐานจริง และคะแนนบนหน้าจอนี้ไม่ใช่ชื่อเสียงจริง",
  "Switch to Real Data": "สลับไปข้อมูลจริง",
  "B2B Business Reputation Signal": "สัญญาณชื่อเสียงธุรกิจ B2B",
  "My Business Reputation": "ชื่อเสียงธุรกิจของฉัน",
  "View My Reputation": "ดูชื่อเสียงของฉัน",
  "Verify a Company": "ตรวจสอบบริษัท",
  "Share Reputation": "แชร์ชื่อเสียง",
  "On-time obligation performance": "การชำระภาระตรงเวลา",
  "Operational transaction signals": "สัญญาณธุรกรรมเชิงปฏิบัติการ",
  "Consistency & liquidity stability": "ความสม่ำเสมอและสภาพคล่อง",
  "Historical activity duration": "ระยะเวลาการทำกิจกรรมที่ผ่านมา",
  "Your Business Reputation is a signal generated from financial and transaction behavior available to FRL. It is intended to support business decisions and does not guarantee future business performance.": "ชื่อเสียงธุรกิจของคุณเป็นสัญญาณที่สร้างจากพฤติกรรมทางการเงินและธุรกรรมที่ FRL มี ใช้สนับสนุนการตัดสินใจทางธุรกิจ และไม่รับประกันผลงานในอนาคต",
  "Is your score ready?": "คะแนนของคุณพร้อมหรือยัง",
  "This is the engine's own assessment of your submitted evidence. FRL does not compute a completion percentage, so none is shown here.": "นี่คือการประเมินของระบบจากหลักฐานที่คุณส่ง FRL ไม่คำนวณเปอร์เซ็นต์ความคืบหน้า จึงไม่แสดงตัวเลขดังกล่าว",
  "Checking": "กำลังตรวจสอบ",
  "Score available": "มีคะแนนแล้ว",
  "Demo Data — Not A Real Score": "ข้อมูลตัวอย่าง — ไม่ใช่คะแนนจริง",
  "Checking the evidence you have submitted.": "กำลังตรวจหลักฐานที่คุณส่งมา",
  "You are viewing a built-in sample profile. FRL has verified nothing here and no score on this screen reflects a real business. Switch to Real Data to work with your own submitted evidence.": "คุณกำลังดูโปรไฟล์ตัวอย่างในระบบ FRL ไม่ได้ยืนยันสิ่งใดที่นี่ และคะแนนบนหน้าจอนี้ไม่สะท้อนธุรกิจจริง สลับไปข้อมูลจริงเพื่อทำงานกับหลักฐานของคุณเอง",
  "FRL cannot calculate a reputation score until sufficient evidence exists. Submit your financial evidence to begin. FRL will then name the exact factors that are still missing rather than estimating how far along you are.": "FRL คำนวณคะแนนชื่อเสียงไม่ได้จนกว่าจะมีหลักฐานเพียงพอ ส่งหลักฐานทางการเงินเพื่อเริ่มต้น FRL จะบอกปัจจัยที่ยังขาดอย่างชัดเจน แทนการประเมินว่าคุณคืบหน้าแค่ไหน",
  "Add Financial Evidence": "เพิ่มหลักฐานทางการเงิน",
  "Factors without evidence": "ปัจจัยที่ยังไม่มีหลักฐาน",
  "FRL will not publish a reputation score until every required factor has evidence. Complete the evidence below and the engine recalculates.": "FRL จะไม่เผยแพร่คะแนนชื่อเสียงจนกว่าทุกปัจจัยที่จำเป็นจะมีหลักฐาน กรอกหลักฐานด้านล่างให้ครบแล้วระบบจะคำนวณใหม่",
  "Complete Financial Evidence": "กรอกหลักฐานทางการเงินให้ครบ",
  "Calculated by the FRL reputation engine from the evidence you submitted. FRL has not independently audited that evidence; it reflects what you have declared.": "คำนวณโดยระบบชื่อเสียงของ FRL จากหลักฐานที่คุณส่ง FRL ไม่ได้ตรวจสอบหลักฐานนั้นอย่างอิสระ ผลสะท้อนสิ่งที่คุณแจ้งไว้",
  "View Reputation Detail": "ดูรายละเอียดชื่อเสียง",
  "Financial evidence": "หลักฐานทางการเงิน",
  "What is available, what is missing, and what each group is used for. A field shown as — was not reported. It is not a zero.": "อะไรมีอยู่ อะไรขาด และแต่ละกลุ่มใช้ทำอะไร ช่องที่แสดงเป็น — คือไม่ได้รายงาน ไม่ใช่ศูนย์",
  "Evidence groups with submitted data:": "กลุ่มหลักฐานที่มีข้อมูลส่งแล้ว:",
  "of": "จาก",
  ". This counts groups, not completeness — FRL publishes a score only when every factor has evidence.": ". นับเป็นกลุ่ม ไม่ใช่ความครบถ้วน FRL เผยแพร่คะแนนเมื่อทุกปัจจัยมีหลักฐานเท่านั้น",
  "Raw financial information is read by the FRL engine to decide whether a reputation can be produced. It is never exposed through public reputation verification.": "ระบบ FRL อ่านข้อมูลการเงินดิบเพื่อตัดสินว่าสร้างชื่อเสียงได้หรือไม่ ข้อมูลนี้จะไม่ถูกเปิดเผยผ่านการยืนยันชื่อเสียงสาธารณะ",
  "Owner actions": "การดำเนินการของเจ้าของ",
  "These are the actions FRL already offers. Nothing on this screen can change a reputation without evidence behind it.": "นี่คือการดำเนินการที่ FRL มีให้อยู่แล้ว ไม่มีสิ่งใดบนหน้านี้ที่เปลี่ยนชื่อเสียงได้หากไม่มีหลักฐานรองรับ",
  "View reputation": "ดูชื่อเสียง",
  "Generate reputation proof": "สร้างหลักฐานชื่อเสียง",
  "Proof unavailable": "ยังสร้างหลักฐานไม่ได้",
  "A reputation proof can only be minted from a scored outcome. Complete your evidence first.": "หลักฐานชื่อเสียงสร้างได้จากผลที่มีคะแนนเท่านั้น กรอกหลักฐานของคุณให้ครบก่อน",
  "Verify a company": "ตรวจสอบบริษัท",
  "Review submitted data": "ตรวจข้อมูลที่ส่งแล้ว",
  "Manage proofs": "จัดการหลักฐาน",
  "Return to search": "กลับไปค้นหา",
  "Check a company's reputation proof or controlled disclosure link before you do business with them. FRL reports the record's real state and shows a score only when that record is valid.": "ตรวจหลักฐานชื่อเสียงหรือลิงก์เปิดเผยแบบควบคุมของบริษัทก่อนทำธุรกิจ FRL รายงานสถานะจริงของบันทึกนั้น และแสดงคะแนนเมื่อบันทึกใช้ได้เท่านั้น",
  "Open verification centre": "เปิดศูนย์ตรวจสอบ",
  "No reputation to show yet": "ยังไม่มีชื่อเสียงให้แสดง",
  "FRL has not produced a score for your evidence, so there is no breakdown, no trend and no analysis to display. Nothing is shown here rather than a partial figure.": "FRL ยังไม่ได้ให้คะแนนจากหลักฐานของคุณ จึงไม่มีรายละเอียด แนวโน้ม หรือการวิเคราะห์ให้แสดง และจะไม่แสดงตัวเลขบางส่วน",
  "See what is missing": "ดูว่าขาดอะไร",
  "Add financial evidence": "เพิ่มหลักฐานทางการเงิน",
  "Your reputation, in detail": "ชื่อเสียงของคุณ แบบละเอียด",
  "How the engine scored you, the factors behind that score, and how it has moved over time.": "ระบบให้คะแนนคุณอย่างไร ปัจจัยเบื้องหลัง และคะแนนเปลี่ยนไปอย่างไรตามเวลา",
  "Demo sample": "ตัวอย่าง",
  "What sits behind the score": "อะไรอยู่เบื้องหลังคะแนน",
  "Why is my score like this?": "ทำไมคะแนนของฉันเป็นแบบนี้",
  "An interpretation of the evidence you submitted, written by the FRL analysis service.": "การตีความหลักฐานที่คุณส่ง เขียนโดยบริการวิเคราะห์ของ FRL",
  "AI analysis": "การวิเคราะห์ด้วย AI",
  "Generated commentary is informational and based strictly on the financial data in your profile. It does not determine your reputation score and is not financial, lending or investment advice.": "ข้อความที่สร้างขึ้นเป็นข้อมูลประกอบ อิงจากข้อมูลการเงินในโปรไฟล์ของคุณเท่านั้น ไม่ได้กำหนดคะแนนชื่อเสียงของคุณ และไม่ใช่คำแนะนำด้านการเงิน สินเชื่อ หรือการลงทุน",
  "Analysing your reputation factors…": "กำลังวิเคราะห์ปัจจัยชื่อเสียงของคุณ…",
  "Analysis unavailable": "ยังไม่มีการวิเคราะห์",
  "Summary": "สรุป",
  "Reported strengths": "จุดแข็งที่รายงาน",
  "Areas to monitor": "จุดที่ควรติดตาม",
  "No analysis has been produced for this evidence.": "ยังไม่มีการวิเคราะห์สำหรับหลักฐานนี้",
  "This signal is generated from the financial and transaction behaviour available to FRL. It supports a business decision; it does not guarantee future performance.": "สัญญาณนี้สร้างจากพฤติกรรมทางการเงินและธุรกรรมที่ FRL มี ใช้สนับสนุนการตัดสินใจทางธุรกิจ และไม่รับประกันผลงานในอนาคต",
  "Verification centre": "ศูนย์ตรวจสอบ",
  "Look up a reputation proof or a controlled disclosure link. FRL reports the record's real state and shows a score only when that record is valid.": "ค้นหาหลักฐานชื่อเสียงหรือลิงก์เปิดเผยแบบควบคุม FRL รายงานสถานะจริงของบันทึก และแสดงคะแนนเมื่อบันทึกใช้ได้เท่านั้น",
  "FRL proof or disclosure reference": "รหัสอ้างอิงหลักฐานหรือลิงก์เปิดเผยของ FRL",
  "Verify": "ตรวจสอบ",
  "A full": "ลิงก์",
  "link or a bare reference both work. FRL checks the record it resolves to; it never accepts a score from the link itself.": "แบบเต็มหรือรหัสอ้างอิงเปล่าๆ ใช้ได้ทั้งคู่ FRL ตรวจบันทึกที่รหัสชี้ไป และไม่เคยรับคะแนนจากตัวลิงก์เอง",
  "Your own references:": "รหัสอ้างอิงของคุณเอง:",
  "Valid proof": "หลักฐานใช้ได้",
  "Reputation verified": "ยืนยันชื่อเสียงแล้ว",
  "This proof is active. FRL shows the reputation recorded when it was issued. The figures below are a snapshot and may have changed since.": "หลักฐานนี้ยังใช้งานอยู่ FRL แสดงชื่อเสียงที่บันทึกตอนออกหลักฐาน ตัวเลขด้านล่างเป็นภาพ ณ ขณะนั้น และอาจเปลี่ยนไปแล้ว",
  "A verified proof supports a business decision. It does not guarantee future business performance.": "หลักฐานที่ยืนยันแล้วช่วยสนับสนุนการตัดสินใจทางธุรกิจ แต่ไม่รับประกันผลงานในอนาคต",
  "Status": "สถานะ",
  "Reputation proofs": "หลักฐานชื่อเสียง",
  "A proof is a dated snapshot of your reputation at a moment in time, produced by the FRL engine from your submitted evidence. Anyone holding the link can read it until it expires or you revoke it.": "หลักฐานคือภาพชื่อเสียงของคุณ ณ ช่วงเวลาหนึ่งที่ระบุวันที่ ออกโดยระบบ FRL จากหลักฐานที่คุณส่ง ใครมีลิงก์ก็อ่านได้จนกว่าจะหมดอายุหรือคุณเพิกถอน",
  "Create Proof": "สร้างหลักฐาน",
  "FRL can only mint a proof from a scored reputation, and you do not have one yet. Complete your financial evidence first; the engine will produce a score, and a proof becomes available at that point.": "FRL สร้างหลักฐานได้จากชื่อเสียงที่มีคะแนนเท่านั้น และคุณยังไม่มี กรอกหลักฐานทางการเงินให้ครบก่อน ระบบจะให้คะแนน แล้วจึงสร้างหลักฐานได้",
  "Active proofs": "หลักฐานที่ใช้งานอยู่",
  "Loading proofs…": "กำลังโหลดหลักฐาน…",
  "Issued": "ออกเมื่อ",
  "Policy": "นโยบาย",
  "Share": "แชร์",
  "View": "ดู",
  "Revoke": "เพิกถอน",
  "Controlled disclosure links": "ลิงก์เปิดเผยแบบควบคุม",
  "A disclosure link releases less than a proof. You choose whether it carries the score alone, the score and level, or the factor results.": "ลิงก์เปิดเผยให้ข้อมูลน้อยกว่าหลักฐาน คุณเลือกได้ว่าจะแสดงคะแนนอย่างเดียว คะแนนกับระดับ หรือผลของแต่ละปัจจัย",
  "Loading disclosures…": "กำลังโหลดลิงก์เปิดเผย…",
  "No disclosure links yet. Create one from an active proof to control what that recipient can see.": "ยังไม่มีลิงก์เปิดเผย สร้างจากหลักฐานที่ใช้งานอยู่เพื่อควบคุมว่าผู้รับเห็นอะไร",
  "Retired proofs": "หลักฐานที่ปลดแล้ว",
  "Submitted financial evidence": "หลักฐานทางการเงินที่ส่งแล้ว",
  "Everything the FRL engine reads from you, and exactly what it is missing. A field shown as — was never reported. It is never treated as zero.": "ทุกอย่างที่ระบบ FRL อ่านจากคุณ และสิ่งที่ยังขาด ช่องที่แสดงเป็น — คือไม่เคยรายงาน และไม่ถูกนับเป็นศูนย์",
  "Update Evidence": "อัปเดตหลักฐาน",
  "No evidence has been submitted yet": "ยังไม่มีหลักฐานที่ส่งมา",
  "FRL cannot calculate a reputation score until sufficient evidence exists. Nothing is held on this workspace, so there is nothing to show and no score to publish.": "FRL คำนวณคะแนนชื่อเสียงไม่ได้จนกว่าจะมีหลักฐานเพียงพอ พื้นที่ทำงานนี้ยังไม่มีข้อมูล จึงไม่มีอะไรให้แสดงและไม่มีคะแนนให้เผยแพร่",
  ". This counts groups rather than completeness, and FRL publishes a score only when every required factor has evidence.": ". นับเป็นกลุ่ม ไม่ใช่ความครบถ้วน และ FRL เผยแพร่คะแนนเมื่อทุกปัจจัยที่จำเป็นมีหลักฐานเท่านั้น",
  "This information is used by FRL to calculate your Business Reputation. Raw financial information is not exposed through public reputation verification.": "FRL ใช้ข้อมูลนี้คำนวณชื่อเสียงธุรกิจของคุณ ข้อมูลการเงินดิบจะไม่ถูกเปิดเผยผ่านการยืนยันชื่อเสียงสาธารณะ",
  "Create disclosure link": "สร้างลิงก์เปิดเผย",
  "Snapshot this link will share": "ภาพที่ลิงก์นี้จะแชร์",
  "How much should this recipient see?": "ผู้รับควรเห็นมากแค่ไหน",
  "When should the link stop working?": "ลิงก์ควรหยุดใช้งานเมื่อไร",
  "The link stops disclosing anything after this date. You can revoke it sooner.": "ลิงก์จะหยุดเปิดเผยข้อมูลหลังวันที่นี้ คุณเพิกถอนก่อนได้",
  "Cancel": "ยกเลิก",
  "Create link": "สร้างลิงก์",
  "These are values you declare. FRL records what you enter here; it has not verified any of it against a bank or an accounting system, and the reputation score is produced by the FRL engine from whatever evidence is present.": "ค่าเหล่านี้คุณเป็นผู้แจ้ง FRL บันทึกสิ่งที่คุณกรอก ยังไม่ได้ตรวจกับธนาคารหรือระบบบัญชี และคะแนนชื่อเสียงสร้างโดยระบบ FRL จากหลักฐานเท่าที่มี",
  "Income & Expenditure": "รายได้และรายจ่าย",
  "Savings & Reserves": "เงินออมและเงินสำรอง",
  "Debt Liabilities": "หนี้สิน",
  "FRL will only produce a score once every required factor has evidence. A factor you cannot evidence is left unscored rather than assumed.": "FRL จะให้คะแนนเมื่อทุกปัจจัยที่จำเป็นมีหลักฐานเท่านั้น ปัจจัยที่คุณไม่มีหลักฐานจะไม่ถูกให้คะแนน ไม่ใช่สันนิษฐาน",
  "Save & Recalculate Engine Score": "บันทึกและคำนวณคะแนนใหม่",
  "PAY": "PAY",
  "BIZ": "BIZ",
  "FIN": "FIN",
  "TXN": "TXN",
  "NO RECORD · NO SIGNAL": "ไม่มีบันทึก · ไม่มีสัญญาณ",
  "REL": "REL",
  "STA": "STA",
  "RES": "RES",
  "LEV": "LEV",
  "TRK": "TRK",
  "CNF": "CNF",
  "SOURCE": "แหล่งที่มา",
  "RETRIEVAL STATUS": "สถานะการดึงข้อมูล",
  "UNKNOWN": "ไม่ทราบ",
  "Sample profile": "โปรไฟล์ตัวอย่าง",
  "FRL home": "หน้าแรก FRL",
  "Main": "เมนูหลัก",
  "Workspace": "พื้นที่ทำงาน",
  "Open menu": "เปิดเมนู",
  "Close menu": "ปิดเมนู",
  "Footer": "ส่วนท้ายเว็บ",
  "Profile view": "มุมมองโปรไฟล์",
  "Breadcrumb": "เส้นทางนำทาง",
  "Profile sections": "ส่วนของโปรไฟล์",
  "Owner workspace sections": "ส่วนของพื้นที่ทำงานเจ้าของ",
  "Data mode": "โหมดข้อมูล",
  "Clear search": "ล้างการค้นหา",
  "Filter results by profile status": "กรองผลตามสถานะโปรไฟล์",
  "Search company by name or registration ID (e.g. Toyota, TechFlow, 01055...)": "ค้นหาบริษัทด้วยชื่อหรือเลขทะเบียน (เช่น Toyota, TechFlow, 01055...)",
  "Company name, registration ID, or jurisdiction…": "ชื่อบริษัท เลขทะเบียน หรือเขตอำนาจรัฐ…",
  "Paste a verification link, proof_… or share_…": "วางลิงก์ยืนยัน, proof_… หรือ share_…",
  "Overview": "ภาพรวม",
  "My score": "คะแนนของฉัน",
  "Check a company": "ตรวจสอบบริษัท",
  "Share my score": "แชร์คะแนนของฉัน",
  "My evidence": "หลักฐานของฉัน",
  "Your score and what to do next.": "คะแนนของคุณและสิ่งที่ต้องทำต่อ",
  "What your score is made of and how it has changed.": "คะแนนของคุณประกอบด้วยอะไร และเปลี่ยนไปอย่างไร",
  "Look up another company’s shared score.": "ดูคะแนนที่บริษัทอื่นแชร์มา",
  "Create and manage links you give to other businesses.": "สร้างและจัดการลิงก์ที่คุณให้ธุรกิจอื่น",
  "The financial records behind your score. Add or review them here.": "บันทึกทางการเงินเบื้องหลังคะแนนของคุณ เพิ่มหรือตรวจดูได้ที่นี่",
  "No financial evidence has been submitted to FRL, so no reputation score can be produced.": "ยังไม่มีหลักฐานทางการเงินที่ส่งให้ FRL จึงสร้างคะแนนชื่อเสียงไม่ได้",
  "No proof exists, and none can be created until your evidence supports a reputation score.": "ยังไม่มีหลักฐานชื่อเสียง และสร้างไม่ได้จนกว่าหลักฐานของคุณจะรองรับคะแนนชื่อเสียง",
  "Your submission": "สิ่งที่คุณส่ง",
  "Your submitted evidence": "หลักฐานที่คุณส่งมา",
  "Sample": "ตัวอย่าง",
  "Available": "มีแล้ว",
  "Missing": "ยังขาด",
  "No record on file": "ไม่มีบันทึกในแฟ้ม",
  "Income & Stability": "รายได้และความมั่นคง",
  "Declared revenue and how long that revenue has held.": "รายได้ที่แจ้งและระยะเวลาที่รายได้นั้นคงอยู่",
  "Expenses & Spending": "ค่าใช้จ่ายและการใช้จ่าย",
  "Declared monthly outgoings and the discretionary share of income.": "รายจ่ายรายเดือนที่แจ้งและสัดส่วนที่ใช้ตามดุลพินิจ",
  "Payments & Obligations": "การชำระเงินและภาระผูกพัน",
  "Obligation history: paid on time, paid late, or missed.": "ประวัติภาระผูกพัน: ชำระตรงเวลา ชำระล่าช้า หรือผิดนัด",
  "The liquid buffer and the monthly contribution building it.": "เงินสำรองสภาพคล่องและเงินออมรายเดือนที่สะสมไว้",
  "Outstanding obligations, available credit and monthly debt service.": "ภาระคงค้าง วงเงินสินเชื่อ และภาระชำระหนี้รายเดือน",
  "Observed activity: volume, account age and returned payments.": "กิจกรรมที่สังเกตได้: ปริมาณ อายุบัญชี และการชำระที่ถูกตีกลับ",
  "Monthly income": "รายได้ต่อเดือน",
  "Income continuity": "ความต่อเนื่องของรายได้",
  "Revenue sources": "แหล่งรายได้",
  "Monthly expenses": "รายจ่ายต่อเดือน",
  "Expense ratio": "สัดส่วนรายจ่าย",
  "Discretionary share": "สัดส่วนรายจ่ายตามดุลพินิจ",
  "Obligations recorded": "ภาระที่บันทึกไว้",
  "Paid on time": "ชำระตรงเวลา",
  "Paid late": "ชำระล่าช้า",
  "Missed": "ผิดนัด",
  "Liquid savings balance": "เงินออมสภาพคล่อง",
  "Monthly contribution": "เงินออมต่อเดือน",
  "Emergency fund cover": "เงินสำรองฉุกเฉินครอบคลุม",
  "Total debt": "หนี้รวม",
  "Credit limit": "วงเงินสินเชื่อ",
  "Monthly debt service": "ภาระชำระหนี้ต่อเดือน",
  "Debt service ratio": "สัดส่วนภาระหนี้",
  "Transactions, last 6 months": "ธุรกรรม 6 เดือนล่าสุด",
  "Account duration": "อายุบัญชี",
  "Returned payments": "การชำระที่ถูกตีกลับ",
  "Invalid proof": "หลักฐานไม่ถูกต้อง",
  "No longer valid": "ใช้ไม่ได้แล้ว",
  "Software Development & IT Consulting": "พัฒนาซอฟต์แวร์และที่ปรึกษาไอที",
  "Thailand": "ประเทศไทย",
  "TechFlow Solutions is an enterprise software provider specializing in cloud migration, custom SaaS solutions, and financial API integrations for modern businesses.": "TechFlow Solutions เป็นผู้ให้บริการซอฟต์แวร์องค์กร เชี่ยวชาญการย้ายระบบขึ้นคลาวด์ โซลูชัน SaaS แบบกำหนดเอง และการเชื่อมต่อ API ทางการเงินสำหรับธุรกิจยุคใหม่",
  "FRL Development Demo Directory": "ไดเรกทอรีตัวอย่างสำหรับพัฒนา FRL",
  "Based on verified payment records showing 98.5% on-time settlement over 12 months.": "อิงจากบันทึกการชำระเงินที่ยืนยันแล้ว แสดงการชำระตรงเวลา 98.5% ในรอบ 12 เดือน",
  "Based on consistent quarterly operating cashflow and audited balance sheets.": "อิงจากกระแสเงินสดจากการดำเนินงานรายไตรมาสที่สม่ำเสมอและงบดุลที่ตรวจสอบแล้ว",
  "Based on over 2,400 verified commercial banking transactions recorded with FRL.": "อิงจากธุรกรรมธนาคารเชิงพาณิชย์ที่ยืนยันแล้วกว่า 2,400 รายการที่บันทึกกับ FRL",
  "Consistently high payment reliability score (840/1000)": "คะแนนความน่าเชื่อถือด้านการชำระเงินสูงสม่ำเสมอ (840/1000)",
  "Zero default or bounced transaction events recorded in 24 months": "ไม่มีการผิดนัดหรือธุรกรรมถูกตีกลับในรอบ 24 เดือน",
  "Strong recurring monthly revenue stream from enterprise contracts": "รายได้ประจำรายเดือนที่แข็งแกร่งจากสัญญาองค์กร",
  "Short company operating history (founded in 2019)": "ประวัติการดำเนินงานของบริษัทยังสั้น (ก่อตั้งปี 2019)",
  "Some financial filings have 90-day reporting lag": "งบการเงินบางรายการรายงานล่าช้า 90 วัน",
  "ISO 27001 Security Certification Achieved": "ได้รับการรับรองความมั่นคงปลอดภัย ISO 27001",
  "Verified cloud security compliance audit passed in Q3 2025.": "ผ่านการตรวจสอบความสอดคล้องด้านความปลอดภัยคลาวด์ที่ยืนยันแล้วในไตรมาส 3 ปี 2025",
  "Enterprise Fintech Integration Milestone": "หมุดหมายการเชื่อมต่อฟินเทคระดับองค์กร",
  "Delivered core payment gateways for 15 regional banking partners.": "ส่งมอบเกตเวย์ชำระเงินหลักให้พันธมิตรธนาคาร 15 แห่งในภูมิภาค",
  "Strategic Technology Partner": "พันธมิตรด้านเทคโนโลยีเชิงกลยุทธ์",
  "Vendor Contract": "สัญญาผู้ขาย",
  "Payment reliability score upgraded after 12 clean billing cycles.": "คะแนนความน่าเชื่อถือด้านการชำระเงินเพิ่มขึ้นหลังรอบบิลปกติ 12 รอบ",
  "Verified Transaction Data": "ข้อมูลธุรกรรมที่ยืนยันแล้ว",
  "Claimed FRL Official Profile and submitted audited financial records.": "รับรองโปรไฟล์ FRL อย่างเป็นทางการและส่งบันทึกการเงินที่ตรวจสอบแล้ว",
  "FRL Official Claim": "การรับรองอย่างเป็นทางการของ FRL",
  "Recorded strategic partnership with Siam Commercial Tech Group.": "บันทึกความร่วมมือเชิงกลยุทธ์กับ Siam Commercial Tech Group",
  "Public Source": "แหล่งสาธารณะ",
  "Company established in Bangkok, Thailand.": "ก่อตั้งบริษัทในกรุงเทพมหานคร ประเทศไทย",
  "Public Registration Record": "บันทึกทะเบียนสาธารณะ",
  "Q3 2026 Tax Certificate Pending Update": "ใบรับรองภาษีไตรมาส 3 ปี 2026 รอการอัปเดต",
  "Company has not yet attached the Q3 tax compliance filing.": "บริษัทยังไม่ได้แนบเอกสารการปฏิบัติตามกฎหมายภาษีไตรมาส 3",
  "Positive Cashflow Trend": "แนวโน้มกระแสเงินสดเป็นบวก",
  "AI analysis observes a 14% improvement in expense management consistency year-over-year.": "การวิเคราะห์ด้วย AI พบว่าความสม่ำเสมอในการจัดการรายจ่ายดีขึ้น 14% เมื่อเทียบกับปีก่อน",
  "Verified Vendor A": "ผู้ขายที่ยืนยันแล้ว A",
  "Smooth communication during project delivery. Payment was processed within agreed timeline.": "สื่อสารราบรื่นตลอดการส่งมอบโครงการ ชำระเงินตามกำหนดที่ตกลง",
  "TechFlow Solutions (Company Owner)": "TechFlow Solutions (เจ้าของบริษัท)",
  "Thank you for your feedback! We appreciate working with your team.": "ขอบคุณสำหรับความเห็น เรายินดีที่ได้ร่วมงานกับทีมของคุณ",
  "stability": "ความมั่นคง",
  "reliability": "ความน่าเชื่อถือ",
  "resilience": "ความยืดหยุ่น",
  "leverage": "สัดส่วนหนี้",
  "official": "ทางการ",
  "counterparty attested": "รับรองโดยคู่ค้า",
  "Has maintained >$50k monthly recurring revenue": "รักษารายได้ประจำรายเดือนเกิน $50k",
  "Paid all supplier invoices within 15 days": "ชำระใบแจ้งหนี้ผู้ขายทั้งหมดภายใน 15 วัน",
  "Paid all 12 monthly invoices for FY2023 on or before the due date.": "ชำระใบแจ้งหนี้รายเดือนทั้ง 12 ใบของปีงบประมาณ 2023 ตรงหรือก่อนกำหนด",
  "Demo Data": "ข้อมูลตัวอย่าง",
  "Standard / Normal Profile (TechFlow)": "โปรไฟล์มาตรฐาน / ปกติ (TechFlow)",
  "High Expense & Discretionary Spending": "ค่าใช้จ่ายสูงและใช้จ่ายตามดุลพินิจมาก",
  "Delayed Payments & Missed Bills": "ชำระล่าช้าและพลาดบิล",
  "Strong Savings & Zero Debt (Excellent)": "เงินออมแข็งแรงและไม่มีหนี้ (ยอดเยี่ยม)",
  "No Financial Data (Baseline / Insufficient)": "ไม่มีข้อมูลการเงิน (พื้นฐาน / ข้อมูลไม่พอ)",
  "Demo Reputation Score (not real)": "คะแนนชื่อเสียงตัวอย่าง (ไม่ใช่ของจริง)",
  "Sample data from a demo profile. This is not a real FRL reputation.": "ข้อมูลตัวอย่างจากโปรไฟล์ทดลอง ไม่ใช่ชื่อเสียง FRL จริง",
  "Calculated engine-side from verified financial behavior.": "คำนวณฝั่งระบบจากพฤติกรรมทางการเงินที่ยืนยันแล้ว",
  "Close": "ปิด",
  "Monthly income (฿)": "รายได้ต่อเดือน (฿)",
  "Income continuity (months)": "ความต่อเนื่องของรายได้ (เดือน)",
  "Number of revenue sources": "จำนวนแหล่งรายได้",
  "Count of distinct revenue streams you can evidence.": "จำนวนแหล่งรายได้ที่แตกต่างกันซึ่งคุณมีหลักฐานยืนยัน",
  "Monthly expenses (฿)": "รายจ่ายต่อเดือน (฿)",
  "Discretionary ratio": "สัดส่วนรายจ่ายตามดุลพินิจ",
  "Share of spending that is non-essential, 0 to 1.": "สัดส่วนรายจ่ายที่ไม่จำเป็น ตั้งแต่ 0 ถึง 1",
  "Liquid savings (฿)": "เงินออมสภาพคล่อง (฿)",
  "Monthly contribution (฿)": "เงินออมต่อเดือน (฿)",
  "Emergency fund (months)": "เงินสำรองฉุกเฉิน (เดือน)",
  "Months of expenses covered.": "จำนวนเดือนของรายจ่ายที่ครอบคลุม",
  "Total outstanding debt (฿)": "หนี้คงค้างรวม (฿)",
  "Total credit limit (฿)": "วงเงินสินเชื่อรวม (฿)",
  "Credit utilisation ratio": "สัดส่วนการใช้วงเงินสินเชื่อ",
  "Drawn credit over total limit, 0 to 1.": "วงเงินที่ใช้ต่อวงเงินรวม ตั้งแต่ 0 ถึง 1",
  "Monthly debt service (฿)": "ภาระชำระหนี้ต่อเดือน (฿)",
  "Transactions (last 6 months)": "ธุรกรรม (6 เดือนล่าสุด)",
  "Account duration (years)": "อายุบัญชี (ปี)",
  "FRL Reputation Assessment": "FRL Reputation Assessment",
  "What is the FRL Score?": "FRL Score คืออะไร?",
  "FRL does not say who is “good” or “bad”, and does not guarantee that any company is 100% trustworthy.": "FRL ไม่ได้บอกว่าใคร “ดี” หรือ “ไม่ดี” และไม่ได้รับรองว่าบริษัทใดน่าเชื่อถือ 100%",
  "FRL is an assessment based on the data and evidence available at the time of assessment, to help users read the overall picture of a reputation more easily.": "FRL เป็นการประเมินจากข้อมูลและหลักฐานที่มีอยู่ ณ เวลาที่ประเมิน เพื่อช่วยให้ผู้ใช้อ่านภาพรวมของ Reputation ได้ง่ายขึ้น",
  "An FRL assessment should not be the only criterion for any business decision, extending credit, or any transaction.": "การประเมินของ FRL ไม่ควรใช้เป็นเกณฑ์เดียวในการตัดสินใจทางธุรกิจ การให้เครดิต หรือการทำธุรกรรมใด ๆ",
  "I understand and agree": "ฉันเข้าใจและยินยอม",
  "How we assess": "วิธีประเมิน",
  "Read how FRL assesses": "อ่านวิธีที่ FRL ประเมิน",
};
